/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_application_tools_memory_Cleaning */

#ifndef _Included_com_application_tools_memory_Cleaning
#define _Included_com_application_tools_memory_Cleaning
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_application_tools_memory_Cleaning
 * Method:    use
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_application_tools_memory_Cleaning_use
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
